services:

    MonitoringBundle\Configuration\Configuration:
        autowire: true
        autoconfigure: true

    MonitoringBundle\Controller\WatchDogController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]

    MonitoringBundle\Service\WatchDog:
        autowire: true
        autoconfigure: true
