services:

    # Example event listener for objects
    # AppBundle\EventListener\TestListener:
    #    class: AppBundle\EventListener\TestListener
    #    tags:
    #        - { name: kernel.event_listener, event: pimcore.object.preUpdate, method: onObjectPreUpdate }

    # configuration
    MonitoringBundle\Configuration\Configuration:
        autowire: true
        autoconfigure: true

    MonitoringBundle\Controller\WatchDogController:
        autowire: true
        autoconfigure: true

    MonitoringBundle\Service\WatchDog:
        autowire: true
        autoconfigure: true

    Pimcore\ExtensionManager:
        autowire: true
        autoconfigure: true

